///////////////////////////////////////////////////////////////////////////////
//  File generated by HDevelop for HALCON/C++ Version 11.0
///////////////////////////////////////////////////////////////////////////////



#ifndef __APPLE__
#  include "HalconCpp.h"
#else
#  ifndef HC_LARGE_IMAGES
#    include <HALCONCpp/HalconCpp.h>
#  else
#    include <HALCONCppxl/HalconCpp.h>
#  endif
#endif



using namespace HalconCpp;


#ifndef NO_EXPORT_MAIN
// Main procedure 
void action()
{
  // stop(); only in hdevelop
}


#ifndef NO_EXPORT_APP_MAIN
int main(int argc, char *argv[])
{
  // Default settings used in HDevelop (can be omitted) 
  SetSystem("width", 512);
  SetSystem("height", 512);
  action();
  return 0;
}
#endif


#endif


